# Generated by Django 2.2 on 2020-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.CharField(max_length=20)),
                ('item_Quanty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
    ]
