# Generated by Django 2.2 on 2020-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useraddress', models.CharField(max_length=100)),
                ('totalprice', models.IntegerField()),
            ],
        ),
    ]
